### ISSUE TITLE
Licensing / Copyright

### ISSUE THREAD

**Issue by codebam** [NotSythe/SythePoke#2]
Awesome project!

I just wanted to ask about licencing / copyright. Currently without any indication of license, although open source, your code is copyrighted by law. Other user's are not legally allowed to modify your work or build upon it.

This is of course your choice, however I would recommend that you use a free (libre, as in freedom) software license such as the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.txt), the [Apache License](https://directory.fsf.org/wiki/License:Apache2.0) or other free software licenses listed here.

https://www.gnu.org/licenses/license-recommendations.html
https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

If you don't want either a license or copyright, you also have the option of releasing it to the public domain using [CC0](https://directory.fsf.org/wiki/License:CC0)

Of course you always have the option of copyright by either leaving it as is, or by writing "Copyright", "©", the date of publication, and your name. ex. "Copyright © 2016 John Smith".

**Comment by NotSythe** [comment]
Hi Sean

It's public domain :) I'll update the readme to reflect this soon.

Best regards
Richard

**Comment by codebam** [comment]
To release it to the Public Domain, you should use CC0 to make it clear you are releasing to the Public Domain as intended. Since saying it is Public Domain in your Readme can be subjective and the Legal definition varies in various countries.

https://creativecommons.org/choose/zero/

**Comment by NotSythe** [comment]
I'd rather not attach any sort of long legal spiel to it. I think most
people know what copyright free / public domain means.

I'll just add it to the header of the files

**Comment by NotSythe** [comment]
Ok my friend I've pushed those changes up. I hope those satisfy you. At the
end of the day public domain is aboutfreeing the subject matter of
legalities, not adding them. I hope you understand :)

Best regards
Richard

**Comment by codebam** [comment]
That's what the CC0 Licence does, it just makes it clear that its public domain. But its your choice, so that's cool. Thanks Richard :)
